### ISSUE TITLE
Problems with Reverse Motion for Ackermann Steering Vehicles Using Nav2 MPPI Controller

### ISSUE THREAD

**Issue by HazemAshraf11** [ros-navigation/navigation2#4425]
**Required Info:**

- Operating System:
  - ubuntu 22.04
- ROS2 Version:
  - Humble
- DDS implementation:
  - rmw_cyclonedds_cpp 

**Issue Description:**

I am encountering significant challenges when using the Nav2 MPPI controller for reverse motion with an Ackermann steering vehicle. While the planned trajectories appear correct, the vehicle fails to follow these trajectories accurately when moving in reverse. The primary issue seems to stem from the steering geometry not being adequately handled by the current controller settings.

#### Steps to reproduce issue
1- Configure an Ackermann steering vehicle with the Nav2 stack and MPPI controller.

2- remove the cost of the PreferForwardCritic (after visualizing the trajectory, I found that this cost makes it very bad in reverse motion).

3- Plan a path that includes reverse segments while using a planning frequency of 0.01 in the behavior tree to see how the vehicle will handle this path with no path updates.

4- Observe the vehicle's behavior while executing the planned path, particularly during the reverse segments.

Here are the parameters for the controller
```
controller_server:
  ros__parameters:
    use_sim_time: True
    speed_limit_topic: "/speed_limit"
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 5.0
      movement_time_allowance: 10.0
    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 4.0
      yaw_goal_tolerance: 1.0
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 75
      model_dt: 0.05
      batch_size: 2000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 1.5
      vx_min: -1.5
      vy_max: 0.0
      wz_max: 0.5
      iteration_count: 1
      prune_distance: 7.5
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "Ackermann"
      visualize: true
      enforce_path_inversion: true
      inversion_xy_tolerance: 0.2
      inversion_yaw_tolerance: 0.3
      TrajectoryVisualizer:
        trajectory_step: 100
        time_step: 10
      AckermannConstraints:
        min_turning_r: 7.0
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 0.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
      PathAlignCritic:
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        forward_preference: true
      TwirlingCritic:
        enabled: true
        twirling_cost_power: 1
        twirling_cost_weight: 10.0

```

#### Expected behavior
The vehicle should accurately follow the planned path in both forward and reverse motions, with steering angles adjusted appropriately for reverse kinematics.  

#### Actual behavior
The vehicle's steering in reverse does not align correctly with the planned path, resulting in significant deviations and failure to follow the intended trajectory.

https://github.com/ros-navigation/navigation2/assets/99565733/50ebeeb1-787d-4a0a-bc9b-5ff58307377f

#### Additional information
I put the base_link in the middle of the two front wheels and the vehicle aligns correctly with the path in forward motion, but very bad in reverse motion.
I trying putting the base_link between the two rear wheels, but that caused the vehicle to not align correctly in both forward and reverse motion, but it's a bit better in the reverse motion than having the base_link between the two front wheels.

I think the problem can be caused by the planner it self as this path is impossible for the vehicle to follow. I am using hybrid A* with the reeds_shepp motion model, and with the right min turning radius.

I not an expert but I think the vehicle geometry ( wheelbase and track width ) should be taken into consideration too while planning the path, not just the min turning radius.
