### ISSUE TITLE
SmacPlanner-Hybrid generate really not optimal path

### ISSUE THREAD

**Issue by FrGrQuim** [ros-navigation/navigation2#4727]
## Bug report

**Required Info:**

- Operating System:
  - Linux ubuntu 22.04
- ROS2 Version:
  - Iron binary
- Version or commit hash:
  - 1.2.9
- DDS implementation:
  - CyclonDDS

#### Steps to reproduce issue
1 - provide to the smac planner two goals that are placed like this:
![Screenshot from 2024-10-21 16-45-54](https://github.com/user-attachments/assets/71ec0467-6c91-4364-a7d8-a523de5718ad)

The smac planner have the following parameters:
```
SmacPlannerHybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      max_iterations: -1
      max_planning_time: 30.0              # max time in s for planner to plan, smooth
      minimum_turning_radius: 1.8         # minimum turning radius in m of path / vehicle
      analytic_expansion_max_length: 2.0
      cost_penalty: 100.0
      use_quadratic_cost_penalty: True
      cache_obstacle_heuristic: True
```

#### Expected behavior
The planner output this kind of path:
![SmacPlanner_opti drawio](https://github.com/user-attachments/assets/3b03e9a2-2c7e-4d4a-8d3f-3264ab298cc5)

#### Actual behavior
The planner outputs these kind of paths.
![Screenshot from 2024-10-21 16-32-36](https://github.com/user-attachments/assets/81bf7b6d-f1a2-49f8-8ae7-dc54fe7d3d0e)
or
![Screenshot from 2024-10-21 16-32-19](https://github.com/user-attachments/assets/332e241c-b98e-4bfa-96db-2081991079c6)

#### Additional information

- When we periodically re-compute the path, sometimes, the SmacPlanner hybrid generates a good path (similar to the one described in the Expected behavior section).
- Our robot follows a rectangular pattern, and this issue seems to always occur in the same corners. In other corners, the SmacPlanner consistently generates a near-optimal path.

Do you have any idea why this behavior occurs and how to fix it?

**Comment by SteveMacenski** [comment]
Sorry for the delay, ROSCon and ROS-I (+ a short vacation) kept me from my terminal.

This does seem concerning to me and worth looking into. Can you create a reproducable example of this happening so that I can personally look into it? We have a nice tool that Dexory put together (https://github.com/botsandus/planner_playground) which you can put in your planner, global costmap parameters and map. Then, you can set the start/goal point so that we can see this in action in a reproducable way to debug. 

The first path you sent seems on the surface reasonable -- like the minimum turning radius is just slightly larger than what the robot can accomplish from its pose, so you need to do that maneuver by the constraints you set on the turning radius. I'd have to see precise start / goal poses and do some math to know if we're on the right side of that calculation or not to know if there's an issue. 

The second path is very weird and clearly not correct. This is actually so simple that the analytic expansion should be able to immediately find a route to that goal without even going through the planning phase. Though I can't tell scale, if its less than `analytic_expansion_max_length`, it should be able to just "do it". 

**What are the green arrows though?** If those are NavigateThroughPose (or eq.) pose constraints that the path has to go through, that would explain all of the 2 images you showed. It very well may not have been possible from the minimum turning radius you set to be able to go from the robot pose into the first arrow around a round-about maneuver. Eyeballing it, it looks a little short to me, but again I'd need reproducable exact numbers to  calculate radiuses based off of to understand if its possible to do the direct path with your settings. If you modestly reduce your turning radius in these examples, does this go away? If so, that would point to the radius of turn you requested given the constraints being smaller than the minimum turning radius the planner is allowed to use. 

I do note that your `cost_penalty` seems very, very high. Not that I think that it is causing issues w.r.t. this current issue, I would like to know if you set that to something more ... modest like `2.0` if this issue persists. It could be that you penalize small amounts of cost so high that it does wacky things which are much, much longer to above some cost. Though, I assume what you're showing is your global costmap and it doesn't show any cost in the planning region (on the other hand, I don't know what that polygon and the points in it are representing or feeding into the costmap or not).

**Comment by SteveMacenski** [comment]
That appears to be more than 0.5 degrees from what the plans show. 

What happens if you set `allow_primitive_interpolation: true`? 

I'm noticing that you have quite a large turning radius / resolution but still a very finite number of angular quantizations (72, by default, by not setting otherwise). Back of the envelope calculations show me that this set of configurations would result in each motion primitive being sufficiently wide to cause leaving 1 cell-bin to be equal to 9-10 angle quantizations -- effectively reducing the resolution of search from 72 to 7-8. That's why a seemingly small change in angle look so large, its not actually searching at the 72 resolution you asked it to due to your kinematic/costmap settings. 

By setting that to `true`, we make more than just pure left/right turns to the extreme to fill in the gaps. That should resolve your issue.

**Comment by FrGrQuim** [comment]
Unfortunately, this parameter is not available in the version we are using (1.2.9).

**Comment by SteveMacenski** [comment]
You'd wamt to upgrade then :-) Iron is [EOL this month](https://docs.ros.org/en/iron/Releases.html), so you would want to upgrade around now anyhow. The other option is looking into a backport of this feature into Iron without breaking ABI, but I'm not sure that's worth your energy if you have to move off of it in the immediate future anyhow

**Comment by SteveMacenski** [comment]
@FrGrQuim any update?

**Comment by alejandro-alonso-isi** [comment]
@SteveMacenski I had the same problem with SmacPlannerHybrid
only when using the navigation_though_poses action with this configuration

 `````
plugin: "nav2_smac_planner/SmacPlannerHybrid" 
      downsample_costmap: false           
      downsampling_factor: 1             
      tolerance: 0.5                     
      allow_unknown: False                 
      max_iterations: 1000000             
      max_on_approach_iterations: 1000    
      max_planning_time: 10.0              
      motion_model_for_search: "DUBIN"    
      angle_quantization_bins: 72        
      analytic_expansion_ratio: 3.5       
      analytic_expansion_max_length: 3.0 
      analytic_expansion_max_cost: 200.0  
      analytic_expansion_max_cost_override: false   
      minimum_turning_radius: 0.4        
      reverse_penalty: 2.0                
      change_penalty: 0.0                 
      non_straight_penalty: 1.0          
      cost_penalty: 3.5                   
      retrospective_penalty: 0.015
      lookup_table_size: 20.0            
      cache_obstacle_heuristic: false     
      debug_visualizations: false         
      use_quadratic_cost_penalty: True
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: True
      smooth_path: True                   
      use_final_approach_orientation: true
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2
`````

![erro](https://github.com/user-attachments/assets/451e1264-4cb5-4554-be27-c67232556bf0)
