### ISSUE TITLE
Fail in loading parameters for controller_server when adding bringup_launch.py into another launch

### ISSUE THREAD

**Issue by dvdmc** [ros-navigation/navigation2#4770]
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04
  - 
- ROS2 Version: Humble
  - 
- Version or commit hash: ros-humble-navigation2	1.1.16-1jammy.20240830.231501
  - 
- DDS implementation: [Eclipse Cyclone DDS](https://cyclonedds.io/)
  - 

#### Steps to reproduce issue

Including the bringup_launch.py into another launch file (for example, in a supposed tb_nav package) and simply map all the arguments using no namespace.

#### Expected behavior
Nav2 is able to do the bringup

#### Actual behavior
I get errors in controller_server:

```
[lifecycle_manager-5] [ERROR] [1732801697.158933701] [lifecycle_manager_localization]: Failed to change state for node: map_server
[lifecycle_manager-5] [ERROR] [1732801697.158979996] [lifecycle_manager_localization]: Failed to bring up all requested nodes. Aborting bringup.
[bt_navigator-10] [INFO] [1732801697.165182434] [bt_navigator]: 
[bt_navigator-10] 	bt_navigator lifecycle node launched. 
[bt_navigator-10] 	Waiting on external lifecycle transitions to activate
[bt_navigator-10] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-10] [INFO] [1732801697.165360277] [bt_navigator]: Creating
[controller_server-6] [INFO] [1732801697.171776012] [controller_server]: Creating controller server
[planner_server-8] [INFO] [1732801697.232687539] [global_costmap.global_costmap]: 
[planner_server-8] 	global_costmap lifecycle node launched. 
[planner_server-8] 	Waiting on external lifecycle transitions to activate
[planner_server-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-8] [INFO] [1732801697.247297223] [global_costmap.global_costmap]: Creating Costmap
[controller_server-6] [INFO] [1732801697.252753698] [local_costmap.local_costmap]: 
[controller_server-6] 	local_costmap lifecycle node launched. 
[controller_server-6] 	Waiting on external lifecycle transitions to activate
[controller_server-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[velocity_smoother-12] [INFO] [1732801697.265705738] [velocity_smoother]: 
[velocity_smoother-12] 	velocity_smoother lifecycle node launched. 
[velocity_smoother-12] 	Waiting on external lifecycle transitions to activate
[velocity_smoother-12] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-13] [INFO] [1732801697.306324939] [lifecycle_manager_navigation]: Creating
[lifecycle_manager-13] [INFO] [1732801697.312174904] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[waypoint_follower-11] [INFO] [1732801697.313905654] [waypoint_follower]: 
[waypoint_follower-11] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-11] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-11] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-11] [INFO] [1732801697.325595632] [waypoint_follower]: Creating
[controller_server-6] [INFO] [1732801697.331784491] [local_costmap.local_costmap]: Creating Costmap
[behavior_server-9] [INFO] [1732801697.400330003] [behavior_server]: 
[behavior_server-9] 	behavior_server lifecycle node launched. 
[behavior_server-9] 	Waiting on external lifecycle transitions to activate
[behavior_server-9] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-13] [INFO] [1732801697.461628676] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-13] [INFO] [1732801697.461703820] [lifecycle_manager_navigation]: Configuring controller_server
[controller_server-6] [INFO] [1732801697.462576347] [controller_server]: Configuring controller interface
[controller_server-6] [INFO] [1732801697.462819862] [controller_server]: getting goal checker plugins..
[controller_server-6] [INFO] [1732801697.463074770] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-6] [INFO] [1732801697.463123176] [local_costmap.local_costmap]: Configuring
[controller_server-6] [INFO] [1732801697.474313005] [local_costmap.local_costmap]: Using plugin "static_layer"
[controller_server-6] [INFO] [1732801697.485957028] [local_costmap.local_costmap]: Subscribing to the map topic (/map) with transient local durability
[ERROR] [kobuki_ros_node-1]: process has died [pid 672, exit code -6, cmd '/root/turtlebot2_ws/install/kobuki_node/lib/kobuki_node/kobuki_ros_node --ros-args --params-file /root/catkin_ws/install/tb_unizar_nav/share/tb_unizar_nav/params/kobuki_params.yaml'].
[controller_server-6] [INFO] [1732801697.487589588] [local_costmap.local_costmap]: Initialized plugin "static_layer"
[controller_server-6] [INFO] [1732801697.487635720] [local_costmap.local_costmap]: Using plugin "obstacle_layer"
[controller_server-6] [INFO] [1732801697.490855754] [local_costmap.local_costmap]: Subscribed to Topics: 
[controller_server-6] [INFO] [1732801697.490970440] [local_costmap.local_costmap]: Initialized plugin "obstacle_layer"
[controller_server-6] [INFO] [1732801697.491212137] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-6] [INFO] [1732801697.493822734] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-6] [INFO] [1732801697.505518077] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-6] [INFO] [1732801697.508044109] [controller_server]: Created goal checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-6] [INFO] [1732801697.509441767] [controller_server]: Controller Server has goal_checker  goal checkers available.
[controller_server-6] [INFO] [1732801697.515445833] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-6] [INFO] [1732801697.518945205] [controller_server]: Setting transform_tolerance to 0.100000
[controller_server-6] [ERROR] [1732801697.533337914] [controller_server]: Couldn't load critics! Caught exception: No critics defined for FollowPath
[controller_server-6] [ERROR] [1732801697.539661116] [controller_server]: Caught exception in callback for transition 10
[controller_server-6] [ERROR] [1732801697.539727130] [controller_server]: Original error: No critics defined for FollowPath
[controller_server-6] [WARN] [1732801697.539763969] [controller_server]: Error occurred while doing error handling.
[controller_server-6] [FATAL] [1732801697.539780076] [controller_server]: Lifecycle node controller_server does not have error state implemented
[lifecycle_manager-13] [ERROR] [1732801697.540161913] [lifecycle_manager_navigation]: Failed to change state for node: controller_server
[lifecycle_manager-13] [ERROR] [1732801697.540239723] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
```

#### Additional information

This is the launchfile I created. Notice that use_namespace, slam, use_localization, and use_composition (trying to follow issue #3644 ) are  set to false. If there is anything wrong with my approach in general and you can tell me it would also be very helpful.

```
import os

import yaml
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, GroupAction
from launch_ros.actions import PushRosNamespace, Node
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare
from ament_index_python.packages import get_package_share_directory
from launch.launch_description_sources import PythonLaunchDescriptionSource

def generate_launch_description():
    # Paths to bringup and custom package
    bringup_dir = get_package_share_directory('nav2_bringup')
    tb_nav_dir = get_package_share_directory('tb_nav')

    # Paths to launch and params files
    bringup_launch_path = os.path.join(bringup_dir, 'launch', 'bringup_launch.py')
    default_nav_params_file = os.path.join(tb_nav_dir, 'params', 'nav2_params.yaml')
    default_kobuki_params_file = os.path.join(tb_nav_dir, 'params', 'kobuki_params.yaml')
    default_map_file = os.path.join(tb_nav_dir, 'maps', 'dummy.yaml')

    # Create the launch configuration variables
    namespace = LaunchConfiguration('namespace')
    use_namespace = LaunchConfiguration('use_namespace')
    slam = LaunchConfiguration('slam')
    map_yaml_file = LaunchConfiguration('map')
    use_sim_time = LaunchConfiguration('use_sim_time')
    nav_params_file = LaunchConfiguration('nav_params_file')
    kobuki_params_file = LaunchConfiguration('kobuki_params_file')
    autostart = LaunchConfiguration('autostart')
    use_composition = LaunchConfiguration('use_composition')
    use_respawn = LaunchConfiguration('use_respawn')
    log_level = LaunchConfiguration('log_level')
    use_localization = LaunchConfiguration('use_localization')
    use_robot_state_pub = LaunchConfiguration('use_robot_state_pub')

    # Map fully qualified names to relative ones so the node's namespace can be prepended.
    # In case of the transforms (tf), currently, there doesn't seem to be a better alternative
    # https://github.com/ros/geometry2/issues/32
    # https://github.com/ros/robot_state_publisher/pull/30
    # TODO(orduno) Substitute with `PushNodeRemapping`
    #              https://github.com/ros2/launch_ros/issues/56
    remappings = [('/tf', 'tf'),
                  ('/tf_static', 'tf_static')]
    
    # Declare launch arguments
    declarenamespace_cmd = DeclareLaunchArgument(
        'namespace', default_value='ugv0', description='Namespace for the robot'
    )
    declare_use_namespace_cmd = DeclareLaunchArgument(
        'use_namespace',
        default_value='False',
        description='Whether to apply a namespace to the navigation stack',
    )
    declare_slam_cmd = DeclareLaunchArgument(
        'slam', default_value='False', description='Whether run a SLAM'
    )
    declare_map_yaml_cmd = DeclareLaunchArgument(
        'map', default_value=default_map_file, description='Full path to map yaml file to load'
    )
    declare_use_localization_cmd = DeclareLaunchArgument(
        'use_localization', default_value='False',
        description='Whether to enable localization or not'
    )
    declare_use_sim_time_cmd = DeclareLaunchArgument(
        'use_sim_time',
        default_value='False',
        description='Use simulation (Gazebo) clock if True',
    )
    declare_nav_params_file_cmd = DeclareLaunchArgument(
        'nav_params_file',
        default_value=default_nav_params_file,
        description='Full path to the ROS2 parameters file to use for all launched nodes',
    )

    declare_kobuki_params_file_cmd = DeclareLaunchArgument(
        'kobuki_params_file',
        default_value=default_kobuki_params_file,
        description='Full path to the ROS2 parameters file to use for all launched nodes',
    )


    declare_autostart_cmd = DeclareLaunchArgument(
        'autostart',
        default_value='True',
        description='Automatically startup the nav2 stack',
    )

    declare_use_composition_cmd = DeclareLaunchArgument(
        'use_composition',
        default_value='False',
        description='Whether to use composed bringup',
    )

    declare_use_respawn_cmd = DeclareLaunchArgument(
        'use_respawn',
        default_value='False',
        description='Whether to respawn if a node crashes. Applied when composition is disabled.',
    )

    declare_log_level_cmd = DeclareLaunchArgument(
        'log_level', default_value='info', description='log level'
    )

    declare_use_robot_state_pub_cmd = DeclareLaunchArgument(
        'use_robot_state_pub',
        default_value='True',
        description='Whether to start the robot state publisher')
    
    declare_kobuki_ros_node = Node(package='kobuki_node',
                                  executable='kobuki_ros_node',
                                  output='both',
                                  parameters=[kobuki_params_file])

    # Locate description TODO: Fix the xacro compilation
    urdf = os.path.join(tb_nav_dir, 'urdf', 'compiled_turtlebot.urdf')
    with open(urdf, 'r') as infp:
        robot_description = infp.read()

    # Group the kobuki_node launch file under the specified namespace
    # kobuki_group = GroupAction(
    #     actions=[
    #         PushRosNamespace(namespace),  # Apply the namespace dynamically
    #         declare_kobuki_ros_node,
    #     ]
    # )

    start_robot_state_publisher_cmd = Node(
        condition=IfCondition(use_robot_state_pub),
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        # namespace=namespace,
        output='screen',
        parameters=[{'use_sim_time': use_sim_time,
                     'robot_description': robot_description}],
        remappings=remappings)


    # Include the bringup launch file
    bringup_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(bringup_launch_path),
        launch_arguments={
            'namespace': namespace,
            'use_namespace': use_namespace,
            'slam': slam,
            'map': map_yaml_file,
            'use_localization': use_localization,
            'use_sim_time': use_sim_time,
            'params_file': nav_params_file,
            'autostart': autostart,
            'use_composition': use_composition,
            'use_respawn': use_respawn,
            'log_level': log_level
        }.items(),
    )

    return LaunchDescription([
        # Declare launch arguments
        declarenamespace_cmd,
        declare_use_namespace_cmd,
        declare_slam_cmd,
        declare_map_yaml_cmd,
        declare_use_localization_cmd,
        declare_use_sim_time_cmd,
        declare_nav_params_file_cmd,
        declare_kobuki_params_file_cmd,        
        declare_autostart_cmd,
        declare_use_composition_cmd,
        declare_use_respawn_cmd,
        declare_log_level_cmd,
        declare_use_robot_state_pub_cmd,
        # Include the kobuki group
        declare_kobuki_ros_node,
        start_robot_state_publisher_cmd,
        # Include the bringup launch file
        bringup_launch,
    ])
``

**Comment by padhupradheep** [comment]
Hey, are you sure, you are passing the right parameter file? I see that controller server complaining about missing critics and so on.

**Comment by dvdmc** [comment]
Hi, this is the parameter file loaded by `default_nav_params_file`, is there any way to confirm it is being loaded?

```
bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator::navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator::navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller/SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      az_max: 3.5
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.5
      vx_min: -0.35
      vy_max: 0.5
      wz_max: 1.9
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      AckermannConstraints:
        min_turning_r: 0.2
      critics: [
        "ConstraintCritic", "CostCritic", "GoalCritic",
        "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
        "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
      # TwirlingCritic:
      #   enabled: true
      #   twirling_cost_power: 1
      #   twirling_cost_weight: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.70
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.7
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.0]
    min_velocity: [-0.5, 0.0, -2.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

loopback_simulator:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    map_frame_id: "map"
    scan_frame_id: "base_scan"  # tb4_loopback_simulator.launch.py remaps to 'rplidar_link'
    update_duration: 0.02
```
