### ISSUE TITLE
[SMAC planner] inflation cost not respected on narrow corridor 

### ISSUE THREAD

**Issue by BriceRenaudeau** [ros-navigation/navigation2#4808]
## Bug report

The path computed by smac planner can go in "inscribed" areas and is not pushed toward middle of free space if the corridor is a bit narrow. When the corridor is a bit wider (2nd image), the path is correct:

![zoom_narrow_path_smoother_not_apply](https://github.com/user-attachments/assets/5afa032a-25b3-4b35-8958-184fd5946382)

![zoom_not_arrow_path_respect_costmap](https://github.com/user-attachments/assets/878bec64-c092-43f6-89b3-969c22f61d5b)

The purple cost is lethal cost and is created using forbidden areas.

- Full path with expansion
![narrow_path_disrespect_costmap](https://github.com/user-attachments/assets/97f5c1d8-43a9-4538-a9e7-bc91e3d376c4)

Another strange behavior is that the smoother is not applied when this bug happens. The blue line is the unsmoothed path, and the green is the smoothed one, In the first image, both paths are the same.

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Iron
- Version or commit hash:
  - iron
- DDS implementation:
  - cyclone

#### Steps to reproduce issue

Create a map with a narrow corridor and plan a path from one side to the other.
It can be reproduced with a smaller test environment and footprint:
![small_map_planner_wrong_path](https://github.com/user-attachments/assets/536e0059-4915-4ae5-9da8-687ad553de63)

#### Expected behavior
The path should respect the costmap and be more in the middle of the free space.

#### Actual behavior
The path doesn't respect the costmap and cut in the 'inscribed' cost.

#### Additional information
The planner config file

```yaml
GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      debug_visualizations: true
      downsample_costmap: false # whether or not to downsample the map
      downsampling_factor: 1 # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.25 # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      allow_unknown: false # allow traveling in unknown space
      max_iterations: -1 # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000 # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 6.0 # max time in s for planner to plan, smooth
      motion_model_for_search: "REEDS_SHEPP" # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 360 # Number of angle bins for search
      analytic_expansion_ratio: 3.5 # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 3.0 # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      minimum_turning_radius: 0.4 # minimum turning radius in m of path / vehicle
      reverse_penalty: 1.01 # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.0 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.0 # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.0 # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.1  # For Hybrid/Lattice nodes: penalty to prefer later maneuvers before earlier 
      lookup_table_size: 1.0 # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      smooth_path: True # If true, does+ a simple and quick smoothing post-processing to the path
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true 
```
Costmap config:
```yaml
  ros__parameters:
    footprint: "[ [0.335, 0.23], [0.335, -0.23], [-0.335, -0.23], [-0.335, 0.23] ]"
    # footprint_padding set in costmap specific yaml

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 2.0
      inflation_radius: 2.0
```
