### ISSUE TITLE
Robot immediately enters recovery when goal is set and aborts

### ISSUE THREAD

**Issue by Flamethr0wer** [ros-navigation/navigation2#4826]
Hello. I am trying to run Nav2 with my differential drive robot but it is behaving in a very strange manner, apparently never even trying to reach the goal. I do not know the cause but modifying the parameters barely seems to make any difference.

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble binaries
- Version or commit hash:
  - I installed nav2 and nav2_bringup through apt
         apt binaries: ros-humble-navigation2	1.1.17-1jammy.20241128.124843
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
Well this is a real robot, but the setup is very similar to Josh Newans' [articubot_one](https://github.com/joshnewans/articubot_one), as I had been following his tutorials, just with 4 wheels and in open-loop. The Nav2 parameters are as follows:
```
amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.8
    beam_skip_threshold: 0.3
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.1
    update_min_d: 0.05
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    set_initial_pose: true
    initial_pose:
      x: 0.616
      y: -2.717
      z: 0.0    # Typically 0.0 for a 2D plane
      yaw: 0.0  # Replace with your desired initial orientation in radians
    scan_topic: scan

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 3000
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    default_nav_to_pose_bt_xml: /home/flamethrower/robot_ws/src/robot/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_through_poses_bt_xml: /home/flamethrower/robot_ws/src/robot/navigate_through_poses_w_replanning_and_recovery.xml
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node
      - nav2_is_battery_charging_condition_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.1
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.3
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2
      yaw_goal_tolerance: 0.2
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.1
      min_vel_y: 0.0
      max_vel_x: 0.2
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.1
      max_speed_xy: 0.26
      min_speed_theta: 0.3
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.1
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.02
      robot_radius: 0.2
      plugins: ["obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
         topic: /scan
         max_obstacle_height: 2.0
         clearing: True
         marking: True
         data_type: "LaserScan"
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.2
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.1
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      always_send_full_costmap: True

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    yaml_filename: "/home/flamethrower/robot_ws/src/robot/worlds/map_keepout.yaml"

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.2
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True
#smoother_server:
#  ros__parameters:
#    use_sim_time: False
#    smoother_plugins: ["SmoothPath"]
#    SmoothPath:
#      plugin: "nav2_constrained_smoother/ConstrainedSmoother"
#      minimum_turning_radius: 0.0

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
      backup_speed: 0.1
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      speed: 0.1
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.3
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
```

maybe the ros2_control YAML file might be relevant as well:
```
controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ["FL_wheel_joint" , "RL_wheel_joint"]
    right_wheel_names: ["FR_wheel_joint", "RR_wheel_joint"]
    wheel_separation: 0.4
    wheel_radius: 0.05

    use_stamped_vel: false

    open_loop: true 

    wheels_per_side: 2
    wheel_separation_multiplier: 5.0
    # left_wheel_radius_multiplier: 0.1
    # right_wheel_radius_multiplier: 0.1

    odom_frame_id: odom
    # pose_covariance_diagonal: [0.2, 0.2, 1000000.0, 1000000.0, 1000000.0, 0.05]
    # twist_covariance_diagonal: [0.2, 0.2, 1000000.0, 1000000.0, 1000000.0, 0.05]
    enable_odom_tf: true

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    velocity_rolling_window_size: 10
```

Then just launch robot_launch.py (the main launch file with ros2_control), localization_launch.py and navigation_launch.py from nav2_bringup and set a goal pose.

#### Expected behavior
The robot should navigate to the goal pose and reach the goal, with AMCL correcting odometry miscalculations.

#### Actual behavior
As soon as a goal is set, the robot does some weird, fluctuating spinning (allegedly a spin) and then a backup, before aborting completely and sometimes restarting the nav2 stack. AMCL also does not do much to locate the robot, in the meantime. Here is a video showing this:
https://github.com/user-attachments/assets/8fd7edfe-e7bf-490e-831a-b7549ec9adf0

And this is the kind of outputs I get in the terminal:
```
[bt_navigator-7] [INFO] [1736098965.681060808] [bt_navigator]: Begin navigating from current location (0.62, -2.72) to (1.90, -0.27)
[bt_navigator-7] [WARN] [1736098965.789454113] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[bt_navigator-7] [WARN] [1736098965.796001421] [bt_navigator_navigate_to_pose_rclcpp_node]: Timed out while waiting for action server to acknowledge goal request for compute_path_to_pose
[bt_navigator-7] [WARN] [1736098965.905846549] [bt_navigator_navigate_to_pose_rclcpp_node]: Node timed out while executing service call to global_costmap/clear_entirely_global_costmap.
[bt_navigator-7] [WARN] [1736098966.021711358] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[bt_navigator-7] [WARN] [1736098966.021980653] [bt_navigator_navigate_to_pose_rclcpp_node]: Node timed out while executing service call to local_costmap/clear_entirely_local_costmap.
[bt_navigator-7] [WARN] [1736098966.092252456] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[bt_navigator-7] [WARN] [1736098966.109678838] [bt_navigator_navigate_to_pose_rclcpp_node]: Timed out while waiting for action server to acknowledge goal request for spin
[planner_server-5] [INFO] [1736098966.122246587] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[controller_server-3] [INFO] [1736098966.128759524] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[bt_navigator-7] [WARN] [1736098966.135833865] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[bt_navigator-7] [WARN] [1736098966.157323201] [bt_navigator_navigate_to_pose_rclcpp_node]: Timed out while waiting for action server to acknowledge goal request for wait
[bt_navigator-7] [WARN] [1736098966.177234733] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[controller_server-3] [INFO] [1736098966.203695092] [local_costmap.local_costmap]: KeepoutFilter: Subscribing to "/costmap_filter_info" topic for filter info...
[bt_navigator-7] [WARN] [1736098966.220161777] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!
[bt_navigator-7] [WARN] [1736098966.220350979] [bt_navigator_navigate_to_pose_rclcpp_node]: Timed out while waiting for action server to acknowledge goal request for backup
[bt_navigator-7] [WARN] [1736098966.234958121] [bt_navigator]: [navigate_to_pose] [ActionServer] Aborting handle.
[bt_navigator-7] [ERROR] [1736098966.279738837] [bt_navigator]: Goal failed
[planner_server-5] [INFO] [1736098966.335012797] [global_costmap.global_costmap]: KeepoutFilter: Subscribing to "/costmap_filter_info" topic for filter info...
[behavior_server-6] [INFO] [1736098966.478729826] [behavior_server]: Running spin
[behavior_server-6] [INFO] [1736098966.492984748] [behavior_server]: Turning 1.57 for spin behavior.
[behavior_server-6] [INFO] [1736098966.499635370] [behavior_server]: Running wait
[behavior_server-6] [INFO] [1736098966.558269677] [behavior_server]: Running backup
[planner_server-5] [INFO] [1736098966.679760690] [global_costmap.global_costmap]: KeepoutFilter: Received filter info from /costmap_filter_info topic.
[planner_server-5] [INFO] [1736098966.679962485] [global_costmap.global_costmap]: KeepoutFilter: Subscribing to "/keepout_filter_mask" topic for filter mask...
[controller_server-3] [INFO] [1736098966.715583337] [local_costmap.local_costmap]: KeepoutFilter: Received filter info from /costmap_filter_info topic.
[controller_server-3] [INFO] [1736098966.715796076] [local_costmap.local_costmap]: KeepoutFilter: Subscribing to "/keepout_filter_mask" topic for filter mask...
[planner_server-5] [WARN] [1736098967.216266231] [global_costmap.global_costmap]: KeepoutFilter: New filter mask arrived from /keepout_filter_mask topic. Updating old filter mask.
[controller_server-3] [WARN] [1736098967.263804151] [local_costmap.local_costmap]: KeepoutFilter: New filter mask arrived from /keepout_filter_mask topic. Updating old filter mask.
[planner_server-5] [WARN] [1736098967.318700298] [planner_server]: Planner loop missed its desired rate of 20.0000 Hz. Current loop rate is 0.8587 Hz
[behavior_server-6] [INFO] [1736098968.795433505] [behavior_server]: spin completed successfully
[behavior_server-6] [INFO] [1736098971.365988487] [behavior_server]: backup completed successfully
[behavior_server-6] [INFO] [1736098971.500243562] [behavior_server]: wait completed successfully
```
