### ISSUE TITLE
Setting minimum_turning_radius to 0 for SmacPlannerHybrid causes error 

### ISSUE THREAD

**Issue by tonynajjar** [ros-navigation/navigation2#4845]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24
- ROS2 Version:
  - Jazzy

#### Steps to reproduce issue

```
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      tolerance: 0.2
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000 
      max_planning_time: 1.5 
      motion_model_for_search: "REEDS_SHEPP" 
      angle_quantization_bins: 64 
      analytic_expansion_ratio: 3.5
      minimum_turning_radius: 0.0
      reverse_penalty: 10.0 
      change_penalty: 0.15 
      non_straight_penalty: 1.50
      cost_penalty: 0.1
      lookup_table_size: 10.0
      cache_obstacle_heuristic: False
      debug_visualizations: false
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10

```

#### Actual behavior

I get `GridBased plugin failed to plan from (10.38, 0.41) to (10.35, -3.65): "Start occupied".` when calling `ComputePathThroughPoses` (although it's really not occupied). Setting it dynamically to e.g. 0.1 fixes the issue

#### Additional information

----

**Comment by SteveMacenski** [comment]
That is not a valid configuration, there must be a non-zero value for the minimum turning radius.

**Comment by SteveMacenski** [comment]
I just updated the docs to mention that as well

**Comment by SteveMacenski** [comment]
I think this can be closed?

**Comment by tonynajjar** [comment]
Just noticed this again, sorry I ghosted, this went under the radar. 

> which can be configured with a minimum control set with in-place rotations that would be virtually allowing stop and rotate maneuvers (in conjunction with some minimum turning radius turning moves as well)

I'm trying to migrate to SmacPlannerLattice (on main) mainly for in-place rotations. This is my configuration:


```
    SMAC:
      plugin: "nav2_smac_planner::SmacPlannerLattice" # In Iron and older versions, "/" was used instead of "::"
      lattice_filepath: "../navigation2/nav2_smac_planner/lattice_primitives/sample_primitives/5cm_resolution/0.5m_turning_radius/diff/output.json" # The filepath to the state lattice graph
      allow_unknown: true # Allow traveling in unknown space
      tolerance: 0.0 # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      max_iterations: 1000000 # Maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000 # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 5.0 # Max time in s for planner to plan, smooth
      analytic_expansion_ratio: 3.5 # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 3.0 # For Hybrid/Lattice nodes The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_max_cost: 200.0 # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      analytic_expansion_max_cost_override: false #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      reverse_penalty: 2.0 # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.05 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.05 # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 2.0 # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      rotation_penalty: 0.0 # Penalty to apply to in-place rotations, if minimum control set contains them
      retrospective_penalty: 0.015
      lookup_table_size: 20.0 # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false # Cache the obstacle map dynamic programming distance expansion heuristic between subsequent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      allow_reverse_expansion: true # If true, allows the robot to use the primitives to expand in the mirrored opposite direction of the current robot's orientation (to reverse).
      coarse_search_resolution: 1 # Number of bins to skip when doing a coarse search for the path. Only used for all_direction goal heading mode.
      goal_heading_mode: "DEFAULT" # DEFAULT, BIDIRECTIONAL, ALL_DIRECTION
      smooth_path: False # If true, does a simple and quick smoothing post-processing to the path
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
```

Now that rotation-in-place are theoretically feasible, I still can't figure out what to tune so that instead of the following paths (see images), I get paths that rotates-in place towards the goal, goes straight until the goal, rotates in place to match goal orientation. (as opposed to curving into the end orientation). Any levers I can pull? I tried `retrospective_penalty`, `rotation_penalty` and `non_straight_penalty` with not luck.

<img width="914" height="391" alt="Image" src="https://github.com/user-attachments/assets/7f53afce-e7c1-4126-8e04-90e08b03f857" />

<img width="687" height="579" alt="Image" src="https://github.com/user-attachments/assets/ea481903-ef48-49ad-b11e-52297fd22f16" />


I also tried to reduce `analytic_expansion_max_length` to something very small to make sure the penalties take effect up until the very end of the path but still not perfect: 

<img width="1096" height="636" alt="Image" src="https://github.com/user-attachments/assets/c362957f-6278-46a6-8d69-09aa9e5a4302" />

P.S: I can open a separate issue if you prefer
