### ISSUE TITLE
Request for Assistance with MPPI Controller Configuration

### ISSUE THREAD

**Issue by thomasankara** [ros-navigation/navigation2#4849]
# Request for Assistance: MPPI Controller Configuration

Hello everyone,  

I am looking for guidance on configuring the **MPPI controller** to optimize my robot's performance. Here’s a specific detail about my navigation setup:

- My robot operates on roads with speed limits ranging from **1 to 15 km/h**.
- When switching to a new road, the **speed limit** is dynamically updated.
- A key variable I use in my controller configuration is `prune_distance`, which is dynamically updated based on the speed limit using the following formula:  
  ```math
  new_prune = 0.3 * (speed_limit * horizon_sec)
  ```

### Problem  
The main issue I am encountering is that I cannot achieve a **stable maximum speed**, even when the robot is traveling on **perfectly straight roads without obstacles**. The planner ensures that the robot stays centered on the road, but the controller doesn't seem to push the robot to its speed limits.  

This is disappointing, as my previous controller (`Pure Pursuit`) allowed the robot to reach its maximum speed **95% of the time** in similar conditions.  

### Question  
Do you have any insights or recommendations to address this issue? Any help in fine-tuning the MPPI controller for better performance would be greatly appreciated!

### My Current Parameters  
Here is my current MPPI controller configuration:  

```yaml
controller_server:
  ros__parameters:
    controller_frequency: 20.0

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 60
      model_dt: 0.05
      batch_size: 1250
      vx_std: 0.3
      vy_std: 0.3
      wz_std: 0.15
      vx_max: 5.0 
      vx_min: -0.35
      vy_max: 2.0
      wz_max: 4.0
      iteration_count: 1
      prune_distance: 8.0
      transform_tolerance: 0.1
      temperature: 0.01
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 8
        time_step: 6
      AckermannConstraints:
        min_turning_r: 0.2
      critics: ["ConstraintCritic", "CostCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "VelocityDeadbandCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: false
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 3.0
      GoalAngleCritic:
        enabled: false
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 253.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 7.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 1.7
        offset_from_furthest: 30
        use_path_orientations: true
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        offset_from_furthest: 30
        threshold_to_consider: 1.7
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
        offset_from_furthest: 20
        threshold_to_consider: 0.3
        max_angle_to_furthest: 1.0
      VelocityDeadbandCritic:
        enabled: true
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities: [0.05, 0.05, 0.05]
```

### Additional Information
- **Dynamic Speed Limits**: Updated in real-time based on the road.
- **Expected Behavior**: The robot should maximize its speed on straight roads while maintaining safety.

I’d greatly appreciate your insights or suggestions on improving this setup!
