### ISSUE TITLE
`nav2_system_tests` Build Fails: `gazebo_ros_pkgs` Not Found

### ISSUE THREAD

**Issue by abdul-mannan-khan** [ros-navigation/navigation2#4901]
I encountered a build failure when trying to compile nav2_system_tests on ROS 2 Humble. The error indicates that gazebo_ros_pkgs cannot be found.

```
--- stderr: nav2_system_tests                            
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findgazebo_ros_pkgs.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "gazebo_ros_pkgs", but CMake did not find one.

  Could not find a package configuration file provided by "gazebo_ros_pkgs"
  with any of the following names:

    gazebo_ros_pkgsConfig.cmake
    gazebo_ros_pkgs-config.cmake

  Add the installation prefix of "gazebo_ros_pkgs" to CMAKE_PREFIX_PATH or
  set "gazebo_ros_pkgs_DIR" to a directory containing one of the above files.
  If "gazebo_ros_pkgs" provides a separate development package or SDK, be
  sure it has been installed.

---
Failed   <<< nav2_system_tests [1.67s, exited with code 1]
```

Tried installing gazebo_ros_pkgs with:

`sudo apt install ros-humble-gazebo-ros-pkgs`
But received an "Unable to locate package" error.

Installed ros-humble-ros-gz with:

`sudo apt-get install ros-humble-ros-gz`

Actual Behavior: The build fails due to missing gazebo_ros_pkgs.

**Request for Help:**
Is gazebo_ros_pkgs still supported for ROS 2 Humble?
Should nav2_system_tests be updated to use an alternative package?
Are there any additional installation steps required for gazebo_ros_pkgs?
Thank you in advance for your help!

**Comment by ewak** [comment]
See https://community.gazebosim.org/t/gazebo-classic-end-of-life/2563

I migrated to harmonic on ubuntu 22.04 circa August 2024.
Here is my ansible playbook you might get some mileage from.

```
---
- hosts: ros_humble_gazebo
  tasks:
    - name: Add osrf foundation GPG key
      ansible.builtin.get_url:
        url: https://packages.osrfoundation.org/gazebo.gpg
        dest: /etc/apt/keyrings/pkgs-osrf-archive-keyring.gpg
        mode: '0644'
        force: true
      become: yes

    - name: Add osrf gazebo repo
      ansible.builtin.apt_repository:
        filename: 'gazebo-stable'
        repo: 'deb [signed-by=/etc/apt/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable jammy main'
        update_cache: yes
      become: yes

    - name: Install simulation gazebo related humble packages
      apt:
        pkg: "{{ packages }}"
      become: yes
      vars:
        packages:
          - ros-humble-ros-gzharmonic
          - ros-humble-ros-gzharmonic-bridge
          - ros-humble-ros-gzharmonic-image
          - ros-humble-ros-gzharmonic-interfaces
          - ros-humble-ros-gzharmonic-sim
          - ros-humble-ros-gzharmonic-sim-demos
          - libgz-sensors6-dev
          - gz-harmonic
          - libgz-sim8-dev
          - rapidjson-dev
          - libopencv-dev
          - libgstreamer1.0-dev
          - libgstreamer-plugins-base1.0-dev
          - gstreamer1.0-plugins-bad
          - gstreamer1.0-libav
          - gstreamer1.0-gl
```
