### ISSUE TITLE
Costmap namespace prevents remapping relative topics

### ISSUE THREAD

**Issue by Martin-Oehler** [ros-navigation/navigation2#4905]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 24.04
- ROS2 Version:
  - Jazzy
- Version or commit hash: ros-jazzy-navigation2	1.3.4-1noble.20250115.215155
- DDS implementation: not relevant

#### Steps to reproduce issue

The costmap nodes are loaded as part of the planner/controller in a namespace, e.g. `local_costmap/local_costmap`. To ensure portability when pushing a new namespace (e.g. `/robot_a/local_costmap/local_costmap` ), I have specified sensor source topics as relative topics, e.g. `topic: lidar_scan`.

In practice, this results in the subscription `/robot_a/local_costmap/lidar_scan` because the cost map is hardcoded to be started in the namespace `local_costmap`. It is not possible to remap the topic to the correct `/robot_a/lidar_scan` in any way. The only thing that works is a relay which introduces an additional copy.

With the current setup, it is not possible to create a portable configuration that works when pushed to a new namespace.

#### Expected behavior

It should be possible to create a nav2 configuration that can be pushed to a new namespace.

#### Actual behavior

It is not possible to create such a configuration without relay nodes that introduce additional copies.

#### Example

Launch file:

```yaml
- arg:
    name: namespace
    default: "robot_a"
- push_ros_namespace:
    namespace: "$(var namespace)"

- node:
    pkg: "nav2_controller"
    exec: "controller_server"
    name: "controller_server"
    output: "screen"
    respawn: "true"
    param:
        - from: $(find-pkg-share nav_launch)/config/nav2_config.yaml
```

Config:

```yaml
/**:
    local_costmap:
        local_costmap:
            ros__parameters:
                update_frequency: 1.0
                publish_frequency: 1.0
                global_frame: map
                robot_base_frame: base_link
                robot_radius: 0.22 
                resolution: 0.05
                height: 5
                width: 5
                track_unknown_space: true
                rolling_window: true
                plugins: ["voxel_layer", "inflation_layer"]
                voxel_layer:
                    plugin: "nav2_costmap_2d::VoxelLayer"
                    enabled: True
                    footprint_clearing_enabled: true
                    publish_voxel_map: True
                    origin_z: 0.0
                    z_resolution: 0.05
                    z_voxels: 16
                    unknown_threshold: 15
                    mark_threshold: 0
                    observation_sources: "lidar"
                    combination_method: 0
                    lidar: 
                        topic: lidar_scan
                        max_obstacle_height: 2.0
                        min_obstacle_height: 0.5
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                        raytrace_max_range: 3.0
                        raytrace_min_range: 0.0
                        clearing: True
                        marking: True
```
