### ISSUE TITLE
controller_server crash

### ISSUE THREAD

**Issue by federica-ciani** [ros-navigation/navigation2#4984]
## Bug report

**Required Info:**

- Operating System: 
  - Ubuntu 22.04.5 LTS
- Computer:
  - HP 255 G8 Notebook PC
- ROS2 Version:
  - ROS2 Humble
- Version or commit hash:
  - 507b3659e6c622d9339b61b53810320b600526a2
- DDS implementation:
  - rmw_cyclonedds_cpp

#### Steps to reproduce issue

Sending a lot of laserscan type data the controller.

#### Expected behavior

No crashes

#### Actual behavior

Sending a lot of laserscan type data the controller server crashes.
It happens several times a day

#### Backtrace

[backtrace.txt](https://github.com/user-attachments/files/19246099/backtrace.txt)

#### Possible solution

We solved by adding a mutex nav2_costmap_2d/plugins/obstacle_layer.cpp before the function `projector_.transformLaserScanToPointCloud`.
Could there be any possible side effects?

**Comment by SteveMacenski** [comment]
I see it [happening here](https://github.com/ros-navigation/navigation2/blob/085d235db0ef0d189ca19315d7c69a359778fc93/nav2_costmap_2d/plugins/obstacle_layer.cpp#L368-L408). Can you compile with debug flags and try again so we can get a full trace? This tutorial will guide you through it: https://docs.nav2.org/tutorials/docs/get_backtrace.html. 

How do you have this layer configured? Unless you're using a multithreaded executor and either (a) both `laserScanValidInfCallback` and `laserScanCallback` are being called or (b) modified so that the subscriptions are in different callback groups, I don't see how there could be a parallel issue. 

> We solved by adding a mutex in nav2_costmap_2d/plugins/obstacle_layer.cpp before the function projector_.transformLaserScanToPointCloud.

Where else is the mutex locking? Its important for us to understand what parallel resources that protects.

**Comment by federica-ciani** [comment]
Thank you for your reply, I will provide the backtrace following your guide.
In the meantime, I will answer you on the other points.
Here the configuration:
```
local_costmap:
    local_costmap:
      ros__parameters:
        always_send_full_costmap: True
        update_frequency: 25.0
        publish_frequency: 25.0
        global_frame: map # TODO by default this is odom
        robot_base_frame: base_link
        rolling_window: True
        width: 10
        height: 10
        resolution: 0.025
        plugins: ["obstacle_layer", "inflation_layer"]
        footprint: '[[-0.36, -0.34], [-0.36, 0.36], [1.0, 0.36], [1.0, -0.34]]'
        lethal_cost_threshold: 100  # new in this file
        map_topic: /map # new in this file
        inflation_layer:
          enabled: True
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 10.0
          inflation_radius: 1.5 #0.4
        obstacle_layer:
          combination_method: 1
          enabled: true
          footprint_clearing_enabled: true
          max_obstacle_height: 2.0
          plugin: nav2_costmap_2d::ObstacleLayer
          observation_sources: camera_right camera_left lidarmulti
          camera_right:
            clearing: true
            data_type: LaserScan
            expected_update_rate: 0.0 # new in this file
            inf_is_valid: true # new in this file
            marking: true
            max_obstacle_height: 2.0
            min_obstacle_height: -1.0
            observation_persistence: 0.0 # new in this file
            obstacle_max_range: 2.8 
            obstacle_min_range: 0.2
            raytrace_max_range: 3.5
            raytrace_min_range: 0.0
            sensor_frame: base_link
            topic: /scan_dx
          camera_left:
            clearing: true
            data_type: LaserScan
            expected_update_rate: 0.0 # new in this file
            inf_is_valid: true # new in this file
            marking: true
            max_obstacle_height: 2.0
            min_obstacle_height: -1.0
            observation_persistence: 0.0 # new in this file
            obstacle_max_range: 2.8 
            obstacle_min_range: 0.2
            raytrace_max_range: 3.5
            raytrace_min_range: 0.0
            sensor_frame: base_link
            topic: /scan_sx
          lidarmulti:
            clearing: true
            data_type: LaserScan
            expected_update_rate: 0.0 # new in this file # TODO
            inf_is_valid: true # new in this file # TODO
            marking: true
            max_obstacle_height: 2.0
            min_obstacle_height: -1.0
            observation_persistence: 0.0 # new in this file # TODO
            obstacle_max_range: 4.5
            obstacle_min_range: 0.05
            raytrace_max_range: 5.0
            raytrace_min_range: 0.0
            sensor_frame: base_link
            topic: /lidar_scan_merged
```
Two cameras work at 6 hz and the lidar at 10 hz.
I can confirm that the executor is single threaded and only the `laserScanValidInfCallback` is called, since the `inf_is_valid` parameter is set to `true` for all sensors. Absolutely I did not change the code in any way.
Furthermore, I can state that with this configuration and data from these sensors the crash occurs every few hours. Whereas by increasing the number of sources and sending laserscans via script the crash occurs more often.
