### ISSUE TITLE
Control Server launching problem

### ISSUE THREAD

**Issue by mark5351-sudo** [ros-navigation/navigation2#5026]
Sorry, I'm new here, I don't know how to troubleshooting this issue. In RViz, the costmap shows a warning, but both the map and laser frames appear to be working fine. However, the log contains two errors: one from [rviz2-3] and another from [controller_server-5].

```
ros2 launch minibot robot_remote_station.launch.py use_slam_option:=online_async_slam
[INFO] [launch]: All log files can be found below /home/rare/.ros/log/2025-03-27-16-36-08-678662-wartier-131508
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [joy_node-1]: process started with pid [131524]
[INFO] [teleop_node-2]: process started with pid [131525]
[INFO] [rviz2-3]: process started with pid [131526]
[INFO] [async_slam_toolbox_node-4]: process started with pid [131527]
[INFO] [controller_server-5]: process started with pid [131528]
[INFO] [smoother_server-6]: process started with pid [131529]
[INFO] [planner_server-7]: process started with pid [131530]
[INFO] [behavior_server-8]: process started with pid [131531]
[INFO] [bt_navigator-9]: process started with pid [131532]
[INFO] [waypoint_follower-10]: process started with pid [131533]
[INFO] [velocity_smoother-11]: process started with pid [131534]
[INFO] [collision_monitor-12]: process started with pid [131539]
[INFO] [opennav_docking-13]: process started with pid [131540]
[INFO] [lifecycle_manager-14]: process started with pid [131541]
[teleop_node-2] [INFO] [1743068170.350041756] [TeleopTwistJoy]: Teleop enable button 0.
[teleop_node-2] [INFO] [1743068170.350109749] [TeleopTwistJoy]: Turbo on button 1.
[teleop_node-2] [INFO] [1743068170.350118931] [TeleopTwistJoy]: Teleop enable inverted reverse.
[teleop_node-2] [INFO] [1743068170.350125731] [TeleopTwistJoy]: Linear axis x on 1 at scale -0.500000.
[teleop_node-2] [INFO] [1743068170.350137262] [TeleopTwistJoy]: Turbo for linear axis x is scale -1.000000.
[teleop_node-2] [INFO] [1743068170.350145834] [TeleopTwistJoy]: Angular axis yaw on 0 at scale 0.500000.
[teleop_node-2] [INFO] [1743068170.350154528] [TeleopTwistJoy]: Turbo for angular axis yaw is scale 1.000000.
[velocity_smoother-11] [INFO] [1743068170.426695276] [velocity_smoother]: 
[velocity_smoother-11] 	velocity_smoother lifecycle node launched. 
[velocity_smoother-11] 	Waiting on external lifecycle transitions to activate
[velocity_smoother-11] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1743068170.464133357] [controller_server]: 
[controller_server-5] 	controller_server lifecycle node launched. 
[controller_server-5] 	Waiting on external lifecycle transitions to activate
[controller_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[smoother_server-6] [INFO] [1743068170.486722918] [smoother_server]: 
[smoother_server-6] 	smoother_server lifecycle node launched. 
[smoother_server-6] 	Waiting on external lifecycle transitions to activate
[smoother_server-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1743068170.498949616] [controller_server]: Creating controller server
[smoother_server-6] [INFO] [1743068170.499295026] [smoother_server]: Creating smoother server
[lifecycle_manager-14] [INFO] [1743068170.502581429] [lifecycle_manager_navigation]: Creating
[planner_server-7] [INFO] [1743068170.510864937] [planner_server]: 
[planner_server-7] 	planner_server lifecycle node launched. 
[planner_server-7] 	Waiting on external lifecycle transitions to activate
[planner_server-7] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-7] [INFO] [1743068170.527158497] [planner_server]: Creating
[lifecycle_manager-14] [INFO] [1743068170.542376283] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[async_slam_toolbox_node-4] [INFO] [1743068170.561232891] [slam_toolbox]: Node using stack size 40000000
[bt_navigator-9] [INFO] [1743068170.567317312] [bt_navigator]: 
[bt_navigator-9] 	bt_navigator lifecycle node launched. 
[bt_navigator-9] 	Waiting on external lifecycle transitions to activate
[bt_navigator-9] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[behavior_server-8] [INFO] [1743068170.569125107] [behavior_server]: 
[behavior_server-8] 	behavior_server lifecycle node launched. 
[behavior_server-8] 	Waiting on external lifecycle transitions to activate
[behavior_server-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-10] [INFO] [1743068170.571822598] [waypoint_follower]: 
[waypoint_follower-10] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-10] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-10] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-10] [INFO] [1743068170.575774869] [waypoint_follower]: Creating
[collision_monitor-12] [INFO] [1743068170.575949938] [collision_monitor]: 
[collision_monitor-12] 	collision_monitor lifecycle node launched. 
[collision_monitor-12] 	Waiting on external lifecycle transitions to activate
[collision_monitor-12] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-9] [INFO] [1743068170.582573371] [bt_navigator]: Creating
[opennav_docking-13] [INFO] [1743068170.582715422] [docking_server]: 
[opennav_docking-13] 	docking_server lifecycle node launched. 
[opennav_docking-13] 	Waiting on external lifecycle transitions to activate
[opennav_docking-13] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[opennav_docking-13] [INFO] [1743068170.582861548] [docking_server]: Creating docking_server
[controller_server-5] [INFO] [1743068170.778380495] [local_costmap.local_costmap]: 
[controller_server-5] 	local_costmap lifecycle node launched. 
[controller_server-5] 	Waiting on external lifecycle transitions to activate
[controller_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1743068170.779168728] [local_costmap.local_costmap]: Creating Costmap
[planner_server-7] [INFO] [1743068170.786184354] [global_costmap.global_costmap]: 
[planner_server-7] 	global_costmap lifecycle node launched. 
[planner_server-7] 	Waiting on external lifecycle transitions to activate
[planner_server-7] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-7] [INFO] [1743068170.787052437] [global_costmap.global_costmap]: Creating Costmap
[async_slam_toolbox_node-4] [INFO] [1743068171.054486903] [slam_toolbox]: Configuring
[async_slam_toolbox_node-4] [INFO] [1743068171.070950802] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-4] [INFO] [1743068171.072705818] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[INFO] [launch.user]: [LifecycleLaunch] Slamtoolbox node is activating.
[async_slam_toolbox_node-4] [INFO] [1743068171.111078936] [slam_toolbox]: Activating
[async_slam_toolbox_node-4] Registering sensor: [Custom Described Lidar]
[joy_node-1] [INFO] [1743068171.255416823] [joy_node]: No haptic (rumble) available, skipping initialization
[joy_node-1] [INFO] [1743068171.255535042] [joy_node]: Opened joystick: Logitech Dual Action.  deadzone: 0.050000
[rviz2-3] [INFO] [1743068171.296389948] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1743068171.296527334] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[lifecycle_manager-14] [INFO] [1743068171.365393732] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-14] [INFO] [1743068171.365454045] [lifecycle_manager_navigation]: Configuring controller_server
[controller_server-5] [INFO] [1743068171.365839662] [controller_server]: Configuring controller interface
[controller_server-5] [INFO] [1743068171.365875324] [controller_server]: getting progress checker plugins..
[controller_server-5] [INFO] [1743068171.366195467] [controller_server]: getting goal checker plugins..
[controller_server-5] [INFO] [1743068171.366658702] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-5] [INFO] [1743068171.366707041] [local_costmap.local_costmap]: Configuring
[controller_server-5] [INFO] [1743068171.378548543] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-5] [INFO] [1743068171.383374342] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-5] [INFO] [1743068171.401215319] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-5] [INFO] [1743068171.401251706] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-5] [INFO] [1743068171.403063662] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[rviz2-3] [INFO] [1743068171.408322750] [rviz2]: Stereo is NOT SUPPORTED
[controller_server-5] [INFO] [1743068171.427204672] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-5] [INFO] [1743068171.427711469] [controller_server]: Controller Server has progress_checker  progress checkers available.
[controller_server-5] [INFO] [1743068171.428431752] [controller_server]: Created goal checker : general_goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-5] [INFO] [1743068171.429608092] [controller_server]: Controller Server has general_goal_checker  goal checkers available.
[controller_server-5] [INFO] [1743068171.431639710] [controller_server]: Created controller : FollowPath of type nav2_mppi_controller::MPPIController
[controller_server-5] [INFO] [1743068171.435606940] [controller_server]: Controller period is equal to model dt. Control sequence shifting is ON
[controller_server-5] [INFO] [1743068171.438154589] [controller_server]: ConstraintCritic instantiated with 1 power and 4.000000 weight.
[rviz2-3] [ERROR] [1743068171.800714571] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1743068171.781082 but the latest data is at time 1743068171.771082, when looking up transform from frame [lidar_frame] to frame [map]
[ERROR] [controller_server-5]: process has died [pid 131528, exit code -4, cmd '/opt/ros/jazzy/lib/nav2_controller/controller_server --ros-args --log-level info --ros-args -p use_sim_time:=False --params-file /tmp/launch_params_6jhirj6y -r /tf:=tf -r /tf_static:=tf_static -r cmd_vel:=cmd_vel_nav'].

```

This my launch file 

```
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node
from launch.substitutions import LaunchConfiguration, PythonExpression
from launch.conditions import IfCondition

def generate_launch_description():

    package_name= 'minibot'
    package_dir= get_package_share_directory(package_name) 

    use_sim_time = LaunchConfiguration('use_sim_time')
    map = LaunchConfiguration('map')
    use_slam_option = LaunchConfiguration('use_slam_option')
    
    declare_use_sim_time= DeclareLaunchArgument(
        'use_sim_time',
        default_value='false',
        description='If true, use simulated clock'
    )  

    declare_map= DeclareLaunchArgument(
        'map',
        default_value='./src/minibot/maps/map_01.yaml',
        description='If true, use simulated clock'
    )

    declare_use_slam_option = DeclareLaunchArgument(
        'use_slam_option',
        default_value='mapper_params_localization',
        description='Choose SLAM option: amcl, mapper_params_localization, or online_async_slam'
    )  

    # Declare the path to files
    joy_params_file = os.path.join(
        get_package_share_directory(package_name), 
        'config', 
        'joystick_params.yaml' 
    )

    rviz_config_file = os.path.join(
        get_package_share_directory(package_name), 
        'config', 
        'minibot_config.rviz' 
    )

    mapper_params_online_async_file = os.path.join(
        package_dir, 
        'config', 
        'mapper_params_online_async.yaml'
    )

    mapper_params_localization_file = os.path.join(
        package_dir, 
        'config', 
        'mapper_params_localization.yaml'
    )

    nav2_params_file = os.path.join(
        package_dir, 
        'config', 
        'nav2_params.yaml'
    )

    # joy node
    joy_node = Node(
        package='joy',
        executable='joy_node',
        parameters=[joy_params_file]
    )    

    # teleop node
    teleop_node = Node(
        package='teleop_twist_joy',
        executable='teleop_node',
        name= 'teleop_node',
        parameters=[joy_params_file],
        remappings=[('/cmd_vel','joy_vel')]
    )   
    
    # rviz2 node
    node_rviz2 = Node(
        package='rviz2',
        executable='rviz2',
        name='rviz2',
        arguments=['-d', rviz_config_file],
        parameters=[{'use_sim_time': False}],
        output='both'
    )
    
    # online_async_slam launch 
    online_async_slam = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('slam_toolbox'),
                    'launch',
                    'online_async_launch.py'
                )]), 
                launch_arguments={
                    'slam_params_file': mapper_params_online_async_file,
                    'use_sim_time': use_sim_time
                }.items(),
                condition=IfCondition(PythonExpression(["'", use_slam_option, "' == 'online_async_slam'"]))         
    )

    # nav2_nmapper_params_localization launch 
    mapper_params_localization = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('slam_toolbox'),
                    'launch',
                    'localization_launch.py'
                )]), 
                launch_arguments={
                    'slam_params_file': mapper_params_localization_file,
                    'use_sim_time': use_sim_time
                }.items(),
                condition=IfCondition(PythonExpression(["'", use_slam_option, "' == 'mapper_params_localization'"]))         
    )

    # amcl launch 
    amcl = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('nav2_bringup'),
                    'launch',
                    'localization_launch.py'
                )]), 
                launch_arguments={
                    'map': map,
                    'use_sim_time': use_sim_time
                }.items(),
                condition=IfCondition(PythonExpression(["'", use_slam_option, "' == 'amcl'"]))           
    )

    # nav2_navigation launch 
    navigation = IncludeLaunchDescription(
                PythonLaunchDescriptionSource([os.path.join(
                    get_package_share_directory('nav2_bringup'),
                    'launch',
                    'navigation_launch.py'
                )]), 
                launch_arguments={
                    'params_file': nav2_params_file,
                    'use_sim_time': use_sim_time
                }.items()            
    )

    

     # Create the launch description and populate
    ld = LaunchDescription()
    
    # Add the launch arguments
    ld.add_action(declare_use_sim_time)
    ld.add_action(declare_map)
    ld.add_action(declare_use_slam_option)

    # Add the nodes to the launch description
    ld.add_action(joy_node)
    ld.add_action(teleop_node)
    ld.add_action(node_rviz2)

    # Add SLAM options
    ld.add_action(online_async_slam)
    ld.add_action(mapper_params_localization)
    ld.add_action(amcl)

    # # Add navigation
    ld.add_action(navigation)

    # Generate the launch description and 
    return ld
```
My parameters
```
amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      ax_max: 3.0
      ax_min: -3.0
      ay_max: 3.0
      az_max: 3.5
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.5
      vx_min: -0.35
      vy_max: 0.5
      wz_max: 1.9
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      AckermannConstraints:
        min_turning_r: 0.2
      critics: [
        "ConstraintCritic", "CostCritic", "GoalCritic",
        "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
        "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
      # TwirlingCritic:
      #   enabled: true
      #   twirling_cost_power: 1
      #   twirling_cost_weight: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.70
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0  
        inflation_radius: 0.05
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.0]
    min_velocity: [-0.5, 0.0, -2.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    # docks: ['home_dock']  # Input your docks here
    # home_dock:
    #   type: 'simple_charging_dock'
    #   frame: map
    #   pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15

loopback_simulator:
  ros__parameters:
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    map_frame_id: "map"
    scan_frame_id: "base_scan"  # tb4_loopback_simulator.launch.py remaps to 'rplidar_link'
    update_duration: 0.02
```
