### ISSUE TITLE
Zone-based behavior tree control using colored map regions

### ISSUE THREAD

**Issue by brayanpa** [ros-navigation/navigation2#5186]
#### Feature description
Hi! I've been thinking about implementing a new functionality that allows drawing zones on the map — something similar to the speed filter. The idea is to define zones by color, for example:

![Image](https://github.com/user-attachments/assets/117c67ac-c4d1-4263-b1ba-129092416403)

You draw a colored image (I was thinking of using .png format), and create the corresponding YAML file:

```
zones:
  elevs_zone_2: [255, 255, 0]
  elev_2_1: [0, 0, 255]
  elev_2_2: [0, 0, 240]
  elev_2_3: [0, 0, 230]
  
  elev_3_1: [0, 0, 220]
  elev_3_2: [0, 0, 210]
  elev_3_3: [0, 0, 200]
  
  door1: [0, 255, 0]
  door2: [0, 240, 0]
  door3: [0, 230, 0]
  door4: [0, 220, 0]
  
  delivery_zone_1: [190, 0, 255]
  delivery_zone_2: [180, 0, 240]
```

Each zone corresponds to a specific RGB color. By reading the color of the pixel that matches the position of base_link, it becomes easy to determine whether the robot is located within a particular zone. This approach could enable services like is_robot_in_zone("ZONE_NAME"), which can be used in a behavior tree to trigger specific actions depending on the robot's current zone. For example, if navigation fails in the "door" zone, the system could fall back to a behavior that requests the door to open. Similarly, if the robot enters the "elevator" zone, it could trigger a service to call the elevator.

I've even thought about implementing a behavior tree node to navigate to a zone.

These are just some ideas I have — I’d really like to hear more points of view. Do you think this would be a useful feature? How would you suggest implementing it? I’m open to all suggestions.
