### ISSUE TITLE
[MPPI] Question on Motion model Lag Compensation

### ISSUE THREAD

**Issue by chanhhoang99** [ros-navigation/navigation2#5214]
Hi there,
Currently, I am working on carrier robot that carries a heavy load.
I witnessed that when the load increase, MPPI controller motion model seems to not take into account the lag in motor and assume the motor can reach desired command velocity instantaneously, isn't it ?

**Comment by SteveMacenski** [comment]
all controllers in Nav2 assume that your robot has properly setup robot controllers to be able to execute commands given. If that is not the case, you would need to change your control system to better be able to handle load changes and/or use the new loaded-robot model to change the dynamic characteristics to represent the dynamics of what the robot can accomplish in the loaded state so the controllers can operate on what the robot is actually capable of accomplishing. 

Its obviously important that the controllers know about what the robot can actually do.  

Your other option is to create your own controller that considers lag and the fact that the robot doesn't actually have the dynamic characteristics you tuned (perhaps tries to estimate these parameters in real-time). Though, its probably easier to either improve your motor control system so that you have better reaction times in the loaded state and/or set the Nav2 controller's dynamic parameters properly for dynamics in the loaded state that require some more time to accelerate / decelerate.

**Comment by chanhhoang99** [comment]
Hi @SteveMacenski ,
About the option of creating a new controller that consider load changes. How about applying a of filter inside MPPI controller.
The idea is to use first-order lag model in MPPI.
Below are steps that I am thinking of:
1. Uses odometry feedback to estimate motor delay dynamically by comparing last commanded velocities and actual velocities.
2. Applies a first-order lag model in the predict function to make velocity predictions realistic.

About implementation steps:
1. Create a new class that inherits MotionModel and overide predict function()
2. Add a function to the new class that will find a time constant ($\tau$) that varies with load using last commanded and actual velocities every controller frequency cycle.
3. Then when predict() function ticks, the time constant ($\tau$) above will be applied to the control sequence.

How do you think about this ?
Ref: https://val-sagrario.github.io/Dynamics%20of%20First%20Order%20Systems%20for%20game%20devs%20-%20Jan%202020.pdf

I have implemented a prototype new motion model and tested on my real system and seems to work with ~250kg load.
I want to share it with you but my nav2 rolling branch is a little bit behind the main branch( I tried latest main branch but encountered build issue with message_fillter headers).
However, I can verify it by real life observation, we saw that it does not deviate from path with heavy load and robot can maneuver U shape, L shape or rotating around pretty good which it couldn't perform with the same configuration using original MotionModel. Though, it would be great if you can suggest a way to compare and branch mark our motion model to verify the idea.

**Comment by SteveMacenski** [comment]
Interesting. Yes, I'd be happy to review / merge a PR introducing that feature! I'm a little surprised something that simple works all that well, but I love the K.I.S.S. principle so if you've tested it and it works well, that's enough for me. I'd just like to hear a few more details about what you saw before vs after this change to sanity check in my mind that this works well enough. But, from your desciption it sounds perfect. If you don't want to share those details publicly, I would understand that and you can email me at steve@opennav.org to chat privately. 

Can you open a draft PR? I can see about the build issues. I can probably just handle that for you. 

I'm curious: do you think this could be applied to other controllers in Nav2 like RPP? That is also common on heavy equipment that would (I imagine) have non-trivial actuation delay. If it can be applied to RPP, then it could be applied to any of them. Perhaps this could even become a shared Controller Utility that is used in the various controllers to abstract the detail

**Comment by chanhhoang99** [comment]
Hi @SteveMacenski 
Could you check the draft here https://github.com/huynhduc9905/navigation2/pull/6/files ?
Please let me know if I should send you some video clips of our testing with this patch.

**Comment by SteveMacenski** [comment]
@chanhhoang99 I took a look and left some comments. I think we can simplify this more and have the lag compensation feature always available but just default disabled. 

>  Please let me know if I should send you some video clips of our testing with this patch.

Sure! Showing some plots along with that improved path tracking would be nice.

**Comment by chanhhoang99** [comment]
Hi @SteveMacenski ,
Just sent you an email with bags and videos. Hope you receive it.

**Comment by vahapt** [comment]
Hi @chanhhoang99 
Please correct me if I'm wrong or missing something. That pull request (https://github.com/ros-navigation/navigation2/pull/5266) seem to be missing. It just changes a few lines to motion model.
The changes proposed here contains many modifications (which should have) but not reflected to the final PR.
https://github.com/huynhduc9905/navigation2/pull/6/files

**Comment by chanhhoang99** [comment]
Hi @vahapt ,
There are two changes in that PR:
1. Apply the tau to compensate motor lag
2. Unclamp control velocity with acceleration constrain in the predict function

The change of tau seems not to take effect, rather than that, the unclamping control velocity with accel seems to solve an issue when the acceleration is low.(e.g < 0.5 m/s^2 or 0.5 rad/s^2).

For large platform, we want to limit acceleration because it has relation with the torque applying on the motor. The higher the accel, the higher the torque on the motor. When the torque seem to exceeds what the motor can generate to win that inertia force generated when robot is moving or rotating with an acceleration, this also causes the overshoot or delay in motor.

So to tackle this, once we came up with two way
1. Let's the MPPI motion model knows this lag and predict.
2. Let's MPPI motion model knows our driver controller limit max acceleration and predict.

So the lag compensation seems not to takes effect much, but when I remove the acceleration constrain from control velocity and also limit max acceleration that my driver controller allow, MPPI motion model is able to predict that acceleration and control the robot with respect to that accel limit.

**Comment by vahapt** [comment]
Your PR changes 4 lines of code.

**Comment by chanhhoang99** [comment]
Yes that change is to solve unfeasible control output generated by the MPPI motion model when the acceleration is set low.

**Comment by vahapt** [comment]
I'll try again but I could not see any big effects. You are testing it by limiting the acceleration on both physical (eg. ros2_control) and ax/az on MPPI controller right?

**Comment by chanhhoang99** [comment]
@vahapt 
I did not use ros2_control, I clamp it my self on the robot driver controller node. But, same idea with ros2_control.
Yes, clamp both on MPPI and controller

Below is my config for 0.1 rad/s^2 and 0.5m/s^2
```
controller_server:
  ros__parameters:
    controller_frequency: 10.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.10
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 50
      model_dt: 0.1
      batch_size: 2000
      ax_max: 0.5
      ax_min: -0.5
      ay_max: 0.0
      az_max: 0.1
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.5
      vx_max: 1.0
      vx_min: 0.0
      vy_max: 0.0
      wz_max: 1.0
      iteration_count: 1
      prune_distance: 10.0
      transform_tolerance: 0.1
      temperature: 0.2
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 20
        time_step: 5
      AckermannConstraints:
        min_turning_r: 0.2
      critics: [
        "ConstraintCritic", "CostCritic", "GoalCritic",
        "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
        "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.2
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
      # TwirlingCritic:
      #   enabled: true
      #   twirling_cost_power: 1
      #   twirling_cost_weight: 10.0
```

**Comment by nicolaloi** [comment]
@chanhhoang99 @SteveMacenski Forgive me if I am wrong, but this PR is making absolutely no changes to vx/wz. The velocities were already limited in the previous version: cvx/cwz were clipped, and then they were copied to vx/wz. What this PR is doing is just skipping a copy.

But this has a side effect of changing the meaning of the gamma cost:
https://github.com/ros-navigation/navigation2/blob/40a04517724acc58a2356a66e2d7f723e1c103d5/nav2_mppi_controller/src/optimizer.cpp#L486
Now the gamma is not computed anymore on the actual "bounded"/limited control used to integrate the trajectories, since the PR removed the clipping of cvx, cwz.

**Comment by SteveMacenski** [comment]
Are you finding that this causes you an issue in your application?

I believe that is the intended meaning in the papers behind the use of the controls in the optimization stage rather than the dynamics-restricted velocities (which are supposed to represent how the vehicle moves based on its dynamic limitations if given that control velocity). 

With that said, since people often have their limitations not set to the extremes of the vehicle but rather the behavior you'd like your robot to have, that would provide the raw control-velocities to the vehicle. This is why we have the stage to do the [post-processing](https://github.com/ros-navigation/navigation2/blob/main/nav2_mppi_controller/src/optimizer.cpp#L293-L340) of those control velocities to ensure they're within the kinematic and dynamic limits set by the user that was used in the motion model in the first place. That should handle that situation.

I look forward to your response. If there's a problem, happy to chat and address it. Maybe the answer would be to have this be a parameter about which method to use. But if you don't see a functional issue, I think this is technically more correct by theory than what we had prior.

**Comment by chanhhoang99** [comment]
Hi @SteveMacenski ,
Should we mention this somewhere in the document ?
For example, if I set max acceleration ax = 0.5m/s^2 for MPPI to predict that constraint, my driver controller should respect that constrain. One particular case when I tested, for example if my robot is moving with max ax = 1.0m/s^2 but in MPPI, we predict with max ax=0.5m/s^2, this would cause an issue for users application.

**Comment by SteveMacenski** [comment]
>  this would cause an issue for users application

I don't think it would, see:

> This is why we have the stage to do the [post-processing](https://github.com/ros-navigation/navigation2/blob/main/nav2_mppi_controller/src/optimizer.cpp#L293-L340) of those control velocities to ensure they're within the kinematic and dynamic limits set by the user that was used in the motion model in the first place

The output is always respecting those acceleration constraints

**Comment by adivardi** [comment]
@chanhhoang99 
If I am following the discussion correctly, #5266 does not solve the lag compensation, right?
Is there a plan to also make a PR for the tao part? or is it not needed in your tests?

**Comment by chanhhoang99** [comment]
@adivardi ,
That PR resolve an issue when acceleration limits are set to low value, it made the robot to move incorrectly.
For the lag compensation, so far I have not yet made progress on that.

**Comment by adivardi** [comment]
@chanhhoang99 
Thanks, I see.
Could you please also explain this change in this PR a bit more?
It is causing oscillations of yaw_vel on my machine. 
It could be that my acceleration constraints are set too high, but I am having trouble understanding your change here to .
(It is quite hard to set `wz_max` & `az_max` for an Ackermann machine, as it depends on the forward speed)

**Comment by SteveMacenski** [comment]
@adivardi can you provide more information on your yaw velocity oscillations? 

If the accelerations are too high, then it effectively disables the use of acceleration in the motion model if they're never achieved. Its basically as if you disabled the acceleration settings. Are you only seeing this now after this PR but didn't beforehand? Or are you generally just seeing this issue?

**Comment by adivardi** [comment]
I am definitely seeing a change in oscillations to the worse with this PR compared to without. I don't want to fully blame this PR, as I am having trouble tuning MPPI as the debugging data (and my experience with mppi) is limited.

For a start: The situation is - vehicle start about 0.5m to the side from a straight path and needs to drive and converge to it. Without this change, I get a bit of oscillations around the path, which settles down. With this change, I get constant oscillations.
This is in simulation.

Without the change:
<img width="1169" height="628" alt="Image" src="https://github.com/user-attachments/assets/2ecdc3bf-ceae-483c-8dd8-26cc60d70213" />

With the change:
<img width="1169" height="628" alt="Image" src="https://github.com/user-attachments/assets/d70d342e-5428-40b0-bc4d-3b62796993f6" />

Regarding tuning - my vehicle is 4-wheel-steering (not too different from Ackermann), so getting yaw limits is tricky since the yaw depends on speed (with max steering you get different yaw at different speed). I would appreciate any tips on tuning this.

For now I set the yaw limits to those that could be achieve at my desired speed of 1.67m/s. However as mppi only achieves a speed of ~0.6m/s (still trying to figure out how to tune for higher speed), these limits are not actually achievable at maximum steering.

```
      ax_max: 2.5
      ax_min: -2.5
      ay_max: 0.0
      ay_min: 0.0
      az_max: 1.8
      vx_max: 1.67 
      vx_min: 0.0  
      vy_max: 0.0
      wz_max: 1.2525
```

Let me know what other data could be useful

**Comment by SteveMacenski** [comment]
What happens if you reduce your accelerations? Does this improve? 

Is the only difference between these plots the PR vs no PR and otherwise same parameters? 

You mention 1.67m/s vs 0.6ms, is that also affected by this PR? Is it possible this is related to tuning and won't be an issue once you have a working config? If you test with Nav2's default provided MPPI Nav2 Bringup params, do you see this same behavior? Maybe its worth trying a baseline we know works well if you're in the midst of param tuning and seeing problems and use that instead to evaluate this PR in your situation.  

@chanhhoang99 any thoughts? This is concerning

**Comment by chanhhoang99** [comment]
I tested on my platform again and observe there are oscillations within this PR as a side effect.
Without PR:

https://github.com/user-attachments/assets/b88fef57-eee7-45ea-868b-56cc3cee3279

With PR

https://github.com/user-attachments/assets/3ed3afc5-19f3-40de-bb1c-41f2accc4c2c

But without this PR, we can't make it work with low acceleration.
@adivardi , could you increase az_max to 5.0rad/s^2 to see if it would reduce the oscillations.

**Comment by chanhhoang99** [comment]
I did some testing to see how wz  oscillations affect to our platform yaw orientation when following a straight path

https://github.com/user-attachments/assets/bb09f6d4-245d-4820-9429-54b61d4f1b98

Although wz oscillations, it seems like robot can still go straight according to the acceleration constrains.

**Comment by chanhhoang99** [comment]
I retune PathAngleCritic and PathAngleCritic, increase controller freq as below config
```
controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.05
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 50
      model_dt: 0.05
      batch_size: 2000
      ax_max: 0.5
      ax_min: -0.5
      ay_max: 0.0
      az_max: 0.5
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.4
      vx_max: 0.5
      vx_min: 0.0
      vy_max: 0.0
      wz_max: 0.5
      iteration_count: 1
      prune_distance: 3.0
      transform_tolerance: 0.1
      temperature: 0.2
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: true
      regenerate_noises: true
      TrajectoryVisualizer:
        trajectory_step: 20
        time_step: 5
      AckermannConstraints:
        min_turning_r: 0.2
      critics: [
        "ConstraintCritic", "CostCritic", "GoalCritic",
        "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
        "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.2
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 2
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 2
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        offset_from_furthest: 2
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.4
        mode: 0
```

Seems like it gives better result on my diff drive model
https://www.youtube.com/watch?v=BrzlP3LjohM&feature=youtu.be
