### ISSUE TITLE
Humble - Slam_toolbox <-> Nav2 - Extrapolation Error: Lookup would require extrapolation

### ISSUE THREAD

**Issue by keshavchintamani** [ros-navigation/navigation2#5227]
Putting this into a blank issue because its unclear if this is a bug or a configuration issue 

Extrapolation issue with Nav2 on a development machine (live) and in Gazebo  (sim). No amount of tuning on Slamtoolbox or Nav2 seems to be fixing it. 

Assuming the root cause is the transform map->odom, seems Slamtoolbox could be the cause, but we see it with AMCL too. 

The symptoms in sim and live are similar, but logs differ (weird odom->map | map <-> odom).. Where we see it:

- Nav2 with AMCL or Slamtoolbox in Gazebo Classic 
- Nav2 with AMCL or Slamtoolbox on live machine

**In simulation, the lookup errors don't always fail the goal
On the robot, the lookup errors fail the goal unless goals are close by or failure_tolerance is increased 2x (our default was 0.4).** 

### Simulation logs 
```
[controller_server-39] [ERROR] [controller_server]: Exception in transformPose: Lookup would require extrapolation into the future.  Requested time 139.700000 but the latest data is at time 139.593000, when looking up transform from frame [odom] to frame [map]
[controller_server-39] [WARN] [controller_server]: Unable to transform robot pose into global plan's frame
[controller_server-39] [ERROR] [controller_server]: Controller patience exceeded
[controller_server-39] [WARN] [controller_server]: [follow_path] [ActionServer] Aborting handle.
[robot_states_node-12] [INFO] [core_states_robot_states_node]: Changing robot state from 'DRIVING' to 'ERROR'
[bt_navigator-42] [WARN] [bt_navigator]: [navigate_to_pose] [ActionServer] Aborting handle.
[bt_navigator-42] [ERROR] [bt_navigator]: Goal failed
```

### Robot Logs 
```
[controller_server-13] [ERROR] [1748847893.777416699] [controller_server]: Extrapolation Error: Lookup would require extrapolation into the future.  Requested time 1748847893.273090 but the latest data is at time 1748847893.236186, when looking up transform from frame [map] to frame [odom]                                                                                                   
[controller_server-13]                                                                                                             
[controller_server-13] [ERROR] [1748847893.777462361] [controller_server]: Global Frame: odom Plan Frame size 26: map              [controller_server-13]                                                                                                             
[controller_server-13] [WARN] [1748847893.777486255] [controller_server]: Could not transform the global plan to the frame of the controller [controller_server-13] [ERROR] [1748847893.777504017] [controller_server]: Controller patience exceeded
[controller_server-13] [WARN] [1748847893.777536741] [controller_server]: [follow_path] [ActionServer] Aborting handle.
[bt_navigator-16] [WARN] [1748847893.801981021] [bt_navigator]: [navigate_to_pose] [ActionServer] Aborting handle.
[bt_navigator-16] [ERROR] [1748847893.802608006] [bt_navigator]: Goal failed
```

### Config
- Operating System: Ubuntu 22.04 
- Computers : Intel i5 and i7 
- ROS2 Version: Humble 
- Nav2 and Slamtoolbox on latest binaries 
	- ros-humble-slam-toolbox/jammy,now 2.6.10-1jammy.20250514.172109
	- ros-humble-nav2-*/jammy,now 1.1.18-1jammy.20250429.210321
- DDS implementation: Cyclone

### Physical 
- Two Sick Nanoscan3 /scan_front /scan_rear into a virtual LIDAR frame node which publishes a single /scan consumed by AMCL/Slamtoolbox
- IMUs and wheel odom to EKF Node publishing /odom
PS: tested passing  scans_front directly to AMCL and Slamtoolbox ->  same results! 
- Nanoscans sync with the navigation pc's chrony which gets its time from an upstream server
- Sim and live launch files are common 

### System Performance Notes (sim/live)
- /odom topic (fused imu + wheels) -> 50hz
```
RESULTS: for map to odom
Chain is: map -> odom
Net delay     avg = 0.00768751: max = 0.144
```
We ran a configurable tf_tester node alongside Nav2 when the symptoms occur 
Our node looks up map->odom and canTransform @ time->now() at 50Hz 
```
ros2 run tf_lookup_tester tf_lookup_tester --ros-args -p source_frame:=map -p target_frame:=odom -p time_out:=0.1 -p lookup_frequency:=50.0 -p use_sim_time:=True
```

### Looked at controller_server.cpp  (humble-main)

Line 677 & 811 
```
rclcpp::Duration tolerance(rclcpp::Duration::from_seconds(costmap_ros_->getTransformTolerance()));
  nav_2d_utils::transformPose(
    costmap_ros_->getTfBuffer(), costmap_ros_->getGlobalFrameID(),
    end_pose_, transformed_end_pose, tolerance);
```
We then ran another node to replicate the above function call  in the same Nav2 run-time
costmap_ros_->getTransformTolerance()  has a value of 0.3 which is the default 
Which does not account for our overrides of transform_tolerance = 0.6 

### The only workaround we found 

Increase controller_server->Failure tolerance which keep the robot from failing less often.  

### Nav2 and Slamtoolbox Configuration

```
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 0.5
      transform_tolerance: 0.6
      global_frame: map
      robot_base_frame: driving_frame

local_costmap:
  local_costmap:
    ros__parameters:
      # increasing this has performance impact
      update_frequency: 5.0
      publish_frequency: 5.0
      transform_tolerance: 0.6
      global_frame: odom
      robot_base_frame: driving_frame

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins:
      [
        "RestrictedDynamicFollowPath", # custom Teb
        "PurePursuitFollowPath", #custom purepursuit 
```

```
slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: slam_map
    base_frame: base_footprint
    scan_topic: scan
    mode: localization

    # if you'd like to start localizing on bringup in a map and pose
    #map_file_name: /path/to/posegraph/no/suffix
    #map_start_pose: [18.5, 5.5, 0.0]
    #map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.125 #if 0 never publishes odometry #20Hz for control loop?
    map_update_interval: 5.0
    resolution: 0.05
    min_laser_range: 1.5 #for rastering images
    max_laser_range: 30.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.4
    tf_buffer_duration: 20. #Duration to store TF messages for lookup. Set high if running offline at multiple times speed in synchronous mode.
    stack_size_to_use: 20000000 #// program needs a larger stack size to serialize large maps

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.15
    scan_buffer_size: 3
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    do_loop_closing: true 
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    loop_search_maximum_distance: 3.0

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
```
